name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Run unit tests
        run: mvn test
        continue-on-error: true

      - name: Publish test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/*.xml

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-world:latest .

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hello-world:latest

      - name: Publish build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: target/*.jar

      - name: Generate Swagger documentation
        run: mvn swagger:generate

      - name: Deploy Swagger to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./path/to/swagger/output

      - name: Send notification to Slack
        if: always()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "channel": "#your-channel",
              "username": "github-actions",
              "text": "Build and deployment completed successfully.",
              "icon_emoji": ":rocket:"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Send notification to Microsoft Teams
        if: always()
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          curl -H 'Content-Type: application/json' -d '{"text": "Build and deployment completed successfully."}' $TEAMS_WEBHOOK_URL

      - name: Send notification to Discord
        if: always()
        run: curl -H 'Content-Type: application/json' -d '{"content": "Build and deployment completed successfully."}' ${{ secrets.DISCORD_WEBHOOK_URL }}
